### ISSUE TITLE
我编译的源码把buildToolsVersion  改为这个版本"23.0.3"，代码发现有错误

### ISSUE THREAD

**Issue by tianshaokai** [jaydenxiao2016/ExpandableTextViewExample#1]
![image](https://cloud.githubusercontent.com/assets/6706496/17991555/50a6854a-6b72-11e6-833b-d8546af7f164.png)

**Comment by jaydenxiao2016** [comment]
选中onFinishInflate，按alt+enter弹出提示，选择一项就行了
