### ISSUE TITLE
作者你的库写的很好，可是我们的需求是这样的，作者是否考虑加一个相对布局的这样的呢

### ISSUE THREAD

**Issue by tianshaokai** [jaydenxiao2016/ExpandableTextViewExample#2]
![image](https://cloud.githubusercontent.com/assets/6706496/17995057/f193d80e-6b90-11e6-8c80-717ec7119d20.png)

**Comment by jaydenxiao2016** [comment]
你可以在根布局LinearLayout下再套一层relatelayout就可以了，把根布局改成relatelayout会报错的，因为ExpandableTextView是继承LinearLayout的

**Comment by jaydenxiao2016** [comment]
![image](https://cloud.githubusercontent.com/assets/19544418/17996238/1162f1a2-6b9a-11e6-955b-c80a653dfeed.png)

**Comment by tianshaokai** [comment]
@jaydenxiao2016  测试后发现    at jaydenxiao.com.expandabletextview.ExpandableTextView2.onMeasure(ExpandableTextView2.java:279)

 java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.RelativeLayout$LayoutParams

还是会报错的

**Comment by tianshaokai** [comment]
@jaydenxiao2016  作者我想改成相对布局的那种该如何写啊，不会测量那块不知道如何入手啊

**Comment by jaydenxiao2016** [comment]
应该不会报错的，按照我给你的那个截图,你再看看是不是你搞错什么了，就是一个布局转化的问题，统一就行了

**Comment by tianshaokai** [comment]
你把你布局贴到 这里边行吗我看看是不是我搞错了

**Comment by tianshaokai** [comment]
`
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:id="@+id/expand_collapse"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:background="@android:color/transparent"
        android:text="@string/collapse"
        android:paddingTop="5dp"
        android:paddingBottom="5dp"
        android:gravity="center"
        android:textColor="@color/main_color"
        android:drawablePadding="3dp"
        android:drawableRight="@drawable/icon_green_arrow_up"
        android:layout_marginTop="5dp" />

    <TextView
        android:id="@+id/expandable_text"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_toLeftOf="@id/expand_collapse"
        android:textColor="@color/gray"
        android:lineSpacingExtra="1dp"
        tools:text="@string/test_content"
        android:ellipsize="end"
        android:textSize="15sp" />

</RelativeLayout>
```

</LinearLayout>

`
外层 是 LinearLayout, 编辑器显示有问题

![image](https://cloud.githubusercontent.com/assets/6706496/18024925/21eb05f4-6c4a-11e6-8766-c4a4f68c33d3.png)

**Comment by jaydenxiao2016** [comment]
我没在电脑前

**Comment by tianshaokai** [comment]
那好吧，以下是我修改后的错误日志
![image](https://cloud.githubusercontent.com/assets/6706496/18024969/410e19f6-6c4c-11e6-9a5b-811003a7326c.png)

**Comment by w2282346548** [comment]
我也遇到这个问题，不知道现在解决了嘛
